#include <windows.h>
#include <tchar.h>
#include "resource.h"
#include <vector>
#include <string>
#include <ctime>

using namespace std;

HWND hList, hCombo, hEdit, hRadio1, hRadio2, hRadio3;
BOOL CALLBACK DlgProc(HWND, UINT, WPARAM, LPARAM);
void FillStudentList(HWND hWnd);
void ShowGradeForSubject(HWND hWnd, int subjectIndex);

vector<vector<string>> students = {
	{"Вася Пельмень", "Гриша Огурец", "Толя Борщ", "Сеня Бублик", "Женя Котлета"},
	{"Миша Блин", "Костя Чебурек", "Лёха Ряженка", "Петя Пельмень", "Федя Лапша", "Слава Укроп"},
	{"Дима Чайник", "Саня Лосось", "Юра Вареник", "Олег Кефир", "Антон Крендель", "Никита Кекс"},
	{"Сергей Гречка", "Паша Омлет", "Игорь Сосиска", "Даня Баклажан", "Егор Чай", "Рома Пирожок", "Жора Борщ"},
	{"Артём Печенька", "Влад Кукурузка", "Ваня Сметана", "Макс Лимонад", "Илья Бублик", "Кирилл Батон"}
};

vector<vector<vector<int>>> grades = {
	{
		{5, 4, 3},
		{4, 5, 5},
		{3, 3, 4},
		{5, 5, 5},
		{4, 3, 4}
	},
	{
		{4, 4, 4},
		{5, 5, 5},
		{3, 4, 4},
		{4, 3, 5},
		{5, 4, 4}
	},//this random info generated by chatgpt
};

int currentSubject = 0;

int WINAPI _tWinMain(HINSTANCE hInstance, HINSTANCE hPrevInst, LPTSTR lpszCmdLine, int nCmdShow)
{
	srand((unsigned int)time(NULL));
	return DialogBox(hInstance, MAKEINTRESOURCE(IDD_DIALOG1), NULL, DlgProc);
}

BOOL CALLBACK DlgProc(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
{
	switch (message)
	{
	case WM_CLOSE:
		EndDialog(hWnd, 0);
		return TRUE;

	case WM_INITDIALOG:
		hCombo = GetDlgItem(hWnd, IDC_COMBO1);
		hList = GetDlgItem(hWnd, IDC_LIST1);
		hEdit = GetDlgItem(hWnd, IDC_EDIT1);
		hRadio1 = GetDlgItem(hWnd, IDC_RADIO1);
		hRadio2 = GetDlgItem(hWnd, IDC_RADIO2);
		hRadio3 = GetDlgItem(hWnd, IDC_RADIO3);

		SendMessage(hCombo, CB_SETITEMHEIGHT, (WPARAM)-1, (LPARAM)20);
		SendMessage(hCombo, CB_SETITEMHEIGHT, 0, (LPARAM)20);

		SetWindowPos(hCombo, NULL, 0, 0, 150, 200, SWP_NOMOVE | SWP_NOZORDER);

		SendMessage(hCombo, CB_RESETCONTENT, 0, 0);
		SendMessage(hCombo, CB_ADDSTRING, 0, (LPARAM)TEXT("Безадри-221"));
		SendMessage(hCombo, CB_ADDSTRING, 0, (LPARAM)TEXT("Безадри-231"));
		SendMessage(hCombo, CB_ADDSTRING, 0, (LPARAM)TEXT("Безадри-232"));
		SendMessage(hCombo, CB_ADDSTRING, 0, (LPARAM)TEXT("Безадри-241"));
		SendMessage(hCombo, CB_ADDSTRING, 0, (LPARAM)TEXT("Безадри-242"));

		SendMessage(hCombo, CB_SETCURSEL, 0, 0);
		FillStudentList(hWnd);
		return TRUE;

	case WM_COMMAND:
		if (HIWORD(wParam) == CBN_SELCHANGE && LOWORD(wParam) == IDC_COMBO1) {
			FillStudentList(hWnd);
		}
		else if (HIWORD(wParam) == BN_CLICKED) {
			if (LOWORD(wParam) == IDC_RADIO1) currentSubject = 0;
			else if (LOWORD(wParam) == IDC_RADIO2) currentSubject = 1;
			else if (LOWORD(wParam) == IDC_RADIO3) currentSubject = 2;

			ShowGradeForSubject(hWnd, currentSubject);
		}
		break;
	}
	return FALSE;
}

void FillStudentList(HWND hWnd)
{
	int index = SendMessage(hCombo, CB_GETCURSEL, 0, 0);
	if (index == CB_ERR) return;

	SendMessage(hList, LB_RESETCONTENT, 0, 0);

	vector<string> group = students[index % students.size()];
	for (const string& name : group)
	{
		SendMessageA(hList, LB_ADDSTRING, 0, (LPARAM)name.c_str());
	}
}

void ShowGradeForSubject(HWND hWnd, int subjectIndex)
{
	int studentIndex = SendMessage(hList, LB_GETCURSEL, 0, 0);
	if (studentIndex == LB_ERR) return;

	int groupIndex = SendMessage(hCombo, CB_GETCURSEL, 0, 0);
	if (groupIndex == CB_ERR) return;

	int grade = grades[groupIndex][studentIndex][subjectIndex];

	TCHAR gradeStr[3];
	_stprintf_s(gradeStr, _T("%d"), grade);

	SetWindowText(hEdit, gradeStr);
}
